#!/usr/bin/env python
import sys, json
from subprocess import call
from shlex import split 

class VidStreamService():
	def __init__(self, configFile):
		with open(configFile, 'r') as f: config = json.loads(f.read())
		self.ip = config['ip']
		self.dev = config['dev']
		self.video = config['video_path']

	def start(self):	
		call(split('ip addr add '+ self.ip + ' dev ' + self.dev))
		call(split("su magic -c \"vlc -vvv "+ self.video +" --sout '#rtp{sdp=rtsp://192.168.189.200:5544/test}' --loop --ttl 1 --daemon\""))

	def stop(self):
		call(split('killall vlc'))
		call(split('ip addr del '+ self.ip + ' dev ' + self.dev))

if __name__ == '__main__':
	vs = VidStreamService('/vlc_service_config.json')
	actionMap = {'start':vs.start , 'stop':vs.stop}
	if sys.argv[1:] and sys.argv[1] in actionMap: actionMap[sys.argv[1]]()
